[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:web]
command=gunicorn --config gunicorn.conf.py --bind 0.0.0.0:5555 app:app
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=BACKUP_DIR=backups,CONFIG_DIR=conf,JINJA_TEMPLATES=jinja,LIBRARY=library,DEBUG=true

[program:ansible]
command=python ansible_worker.py
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=ANSIBLE_STDOUT_CALLBACK="debug",PYTHONUNBUFFERED="1",DEBUG="true",ANSIBLE_FORCE_COLOR="True",ANSIBLE_VAULT_PASSWORD="%(ENV_ANSIBLE_VAULT_PASSWORD)s"

#[program:scheduler]
#; Use the full path to your python executable
#command=python scheduler.py
#directory=/path/to/your/project
#user=your-user
#autostart=true
#autorestart=true
#; This ensures logs from your 'print' and 'logger' statements show up in supervisor logs
#stdout_logfile=/var/log/scheduler.out.log
#stderr_logfile=/var/log/scheduler.err.log
#environment=PYTHONUNBUFFERED=1,BACKUP_DIR=backups,CONFIG_DIR=conf,JINJA_TEMPLATES=jinja,LIBRARY=library,KEY_FILE=/Users/dgoldgar/.ssh/five,DEBUG=true
